#pragma once

#define PERSEUSSDK_VER_MAJOR 1
#define PERSEUSSDK_VER_MINOR 0
#define PERSEUSSDK_VER_PATCH 3

#define PERSEUSSDK_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define PERSEUSSDK_VERSION PERSEUSSDK_TO_VERSION(PERSEUSSDK_VER_MAJOR, PERSEUSSDK_VER_MINOR, PERSEUSSDK_VER_PATCH)