#pragma once

#define PERSEUSLIB_VER_MAJOR 1
#define PERSEUSLIB_VER_MINOR 0
#define PERSEUSLIB_VER_PATCH 3

#define PERSEUSLIB_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define PERSEUSLIB_VERSION PERSEUSLIB_TO_VERSION(PERSEUSLIB_VER_MAJOR, PERSEUSLIB_VER_MINOR, PERSEUSLIB_VER_PATCH)